name: Trigger Workflow in Repository deepak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository B Workflow
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            --request POST \
            --data '{"event_type": "do-something"}' \
            https://api.github.com/repos/deepakcis/Cron_testing/dispatches
