name: Trigger Second Account Workflow
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Second Account Workflow
        env:
          SECOND_GITHUB_PAT: ${{ secrets.AUTH_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.AUTH_TOKEN }}"\
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/deepakcis/Cron_testing/actions/workflows/trigger_cron.yml/dispatches \
          -d '{"ref":"main"}'
