name: 'Workflow of Parent REPO'

on:  
  workflow_dispatch:

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Parent REPO"
      - name: Trigger workflow in another GitHub account
        env:
          GITHUB_PAT: ${{ secrets.D_PAT }}  # Your PAT with appropriate permissions
        run: |
          curl -X POST \
            -H "Authorization: Bearer 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" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/deepakcis/Cron_testing/actions/workflows/trigger_cron/dispatches \
            -d '{"ref":"main"}'
          
