name: 'Workflow of Parent REPO'

on:  
  workflow_dispatch:

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Parent REPO"
      - name: Trigger workflow in another GitHub account
        env:
          GITHUB_PAT: ${{ secrets.DEEPAK_PAT }}  # Your PAT with appropriate permissions
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.DEEPAK_PAT }}" \
          --request POST \
          --data '{"event_type": "do-something"}' \
          https://api.github.com/repos/deepakcis/Cron_testing/dispatches
